spring.application.name=Dawson_Bungalow
spring.mongodb.uri=mongodb+srv://nilushawijerathne1:leomord123@cluster0.tsj2y.mongodb.net/DawsonBungalow?retryWrites=true&w=majority
spring.mongodb.database=DawsonBungalowDB

# JWT
jwt.secret=mySecretKeyThatIsAtLeast32CharactersLong!
jwt.expiration=86400000

# GridFS / Multipart file upload limits
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
