spring.application.name=Dawson_Bungalow
spring.mongodb.uri=mongodb+srv://nilushawijerathne1:leomord123@cluster0.tsj2y.mongodb.net/DawsonBungalow?retryWrites=true&w=majority
spring.mongodb.database=DawsonBungalowDB

# JWT
jwt.secret=mySecretKeyThatIsAtLeast32CharactersLong!
jwt.expiration=86400000

# Base URL - CRITICAL for image URLs
app.base-url=https://newdawson-production.up.railway.app

# GridFS / Multipart file upload limits
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB

# Pinecone
pinecone.api-key=pcsk_2UupW9_BTek8vXbF7TN7ewyUjGS8QYHSkRzZW6HiscjLJQNnkoCcoyYwTe7esvkzerxYbi
pinecone.index=dawsonbungalow
pinecone.index-url=https://dawsonbungalow-3nq03gf.svc.aped-4627-b74a.pinecone.io

# Groq

groq.api.key=${GROQ_API_KEY}
groq.model=llama-3.3-70b-versatile
